
# **1. Basic Array Manipulation:**


Create a 1D array with values ranging from 0 to 9.


In [1]:
import numpy as np

In [2]:
array = np.arange(0,10)
array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Reshape the array into a 3x3 matrix.

Explore Reshape Function

In [3]:
array = np.arange(0,9)  
reshape_array= array.reshape(3, 3)
print(reshape_array)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


Access the element at the second row, second column.

In [4]:
array = np.arange(9).reshape(3, 3)  
element = array[1, 1]  
print(element)

4


Perform element-wise addition, subtraction, multiplication, and division on two arrays [1, 2, 3] and [4, 5, 6].


In [5]:
list_1_arr=np.array([1,2,3])
list_2_arr=np.array([4,5,6])
list_1_arr+list_2_arr

array([5, 7, 9])

In [6]:
list_1_arr=np.array([1,2,3])
list_2_arr=np.array([4,5,6])
list_1_arr-list_2_arr

array([-3, -3, -3])

In [7]:
list_1_arr=np.array([1,2,3])
list_2_arr=np.array([4,5,6])
list_1_arr*list_2_arr

array([ 4, 10, 18])

In [8]:
list_1_arr=np.array([1,2,3])
list_2_arr=np.array([4,5,6])
list_1_arr/list_2_arr

array([0.25, 0.4 , 0.5 ])

Find the sum, mean, and standard deviation of the array [1, 2, 3, 4, 5].


In [9]:
list_array=np.array([1,2,3,4,5])
np.sum(list_array)

15

In [10]:
list_array=np.array([1,2,3,4,5])
np.mean(list_array)

3.0

In [11]:
list_array=np.array([1,2,3,4,5])
np.std(list_array)

1.4142135623730951

Reshape the array [1, 2, 3, 4, 5, 6] into a 2x3 array.

Explore Reshape

In [12]:
list_arr=np.array([1,2,3,4,5,6])
np.reshape(list_arr,(2,3))

array([[1, 2, 3],
       [4, 5, 6]])


# **2. Indexing and Slicing:**


Create a 5x5 array with random integers.


In [13]:
import numpy as np
random_array = np.random.randint(0, 10, size=(5, 5))
print(random_array)

[[6 8 1 5 7]
 [2 2 2 4 9]
 [1 5 0 0 9]
 [8 4 6 9 6]
 [4 0 8 6 5]]


Replace all values in the sub-array with a specific value.

In [14]:
random_array = np.random.randint(0, 10, size=(5, 5))
random_array[1:4, 1:4] = 44
print(random_array)

[[ 1  6  5  5  7]
 [ 1 44 44 44  3]
 [ 7 44 44 44  1]
 [ 8 44 44 44  5]
 [ 7  2  1  6  4]]


Extract the subarray [[3, 4], [7, 8]] from the array [[1, 2], [3, 4], [5, 6], [7, 8]].

In [15]:
my_array=np.array([[1, 2], [3, 4], [5, 6], [7, 8]])
subarray=my_array[[1,3]]
print(subarray)

[[3 4]
 [7 8]]



# **3. Broadcasting:**

Create a 2D array of shape (3, 3) with values from 0 to 2.


### using Title method

In [16]:
array=np.array([0,1,2])
array
new_array=np.tile(array,(3,1))
new_array

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]])

Add a 1D array of shape (3,) to each row of the 2D array using broadcasting.

In [17]:
array_1d=np.array([3,6,9])
array_2d=np.array([[0,1,2],[3,1,0],[1,0,2]])
add_arr=array_1d+array_2d
print(add_arr)

[[ 3  7 11]
 [ 6  7  9]
 [ 4  6 11]]


# **4. Concatenation and Splitting**


1.   Create two 2D arrays of shape (3, 3) with random integers.
2.   Concatenate them horizontally and vertically.
3.   Split the concatenated arrays back into the original arrays.

In [18]:
random_array_1=np.random.randint(0,10,size=(3,3))
random_array_2=np.random.randint(10,18, size=(3,3))
concantenate_horizantal=np.hstack((random_array_1,random_array_2))
print("concantenate_horizantal")
print(concantenate_horizantal)
split_horizantal=np.hsplit(concantenate_horizantal,2)
print("split_horizantal")
print(split_horizantal[0])
print(split_horizantal[1])

concantenate_horizantal
[[ 2  8  5 12 10 11]
 [ 8  5  8 17 16 13]
 [ 9  2  1 17 16 12]]
split_horizantal
[[2 8 5]
 [8 5 8]
 [9 2 1]]
[[12 10 11]
 [17 16 13]
 [17 16 12]]


In [19]:
concantenate_vertical=np.vstack((random_array_1,random_array_2))
print("concantenate_vertical")
print(concantenate_vertical)
split_vertical=np.vsplit(concantenate_vertical,2)
print("split_vertical")
print(split_vertical[0])
print(split_vertical[1])

concantenate_vertical
[[ 2  8  5]
 [ 8  5  8]
 [ 9  2  1]
 [12 10 11]
 [17 16 13]
 [17 16 12]]
split_vertical
[[2 8 5]
 [8 5 8]
 [9 2 1]]
[[12 10 11]
 [17 16 13]
 [17 16 12]]


# **Bonus Question**

Find mode of this array  = [1,2,1,2,3,4,5,6,8,9,1,2,2,22,21,1,1,1,1,2,5]

Hint: Use count and also loop

In [20]:
from scipy import stats
array=np.array([1,2,1,2,3,4,5,6,8,9,1,2,2,22,21,1,1,1,1,2,5])
print(stats.mode(array))

ModeResult(mode=1, count=7)


# **Notes**


1.   All the Questions carry Equal Points (2 points)

2.   Bonus Question carry 5 points

3.   Review lecture for any query

Good Luck!

