
# **1. Basic Array Manipulation:**


Create a 1D array with values ranging from 0 to 9.


In [1]:
import numpy as np

In [2]:
array = np.arange(0,9)
array

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

Reshape the array into a 3x3 matrix.

Explore Reshape Function

In [3]:
array = np.arange(0,9)  
matrix = array.reshape(3, 3)
print(matrix)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


Access the element at the second row, second column.

In [4]:
array = np.arange(9).reshape(3, 3)  
element = array[1, 1]  
print(element)

4


Perform element-wise addition, subtraction, multiplication, and division on two arrays [1, 2, 3] and [4, 5, 6].


In [5]:
list_1_arr=np.array([1,2,3])
list_2_arr=np.array([4,5,6])
list_1_arr+list_2_arr

array([5, 7, 9])

In [6]:
list_1_arr=np.array([1,2,3])
list_2_arr=np.array([4,5,6])
list_1_arr-list_2_arr

array([-3, -3, -3])

In [7]:
list_1_arr=np.array([1,2,3])
list_2_arr=np.array([4,5,6])
list_1_arr*list_2_arr

array([ 4, 10, 18])

In [8]:
list_1_arr=np.array([1,2,3])
list_2_arr=np.array([4,5,6])
list_1_arr/list_2_arr

array([0.25, 0.4 , 0.5 ])

Find the sum, mean, and standard deviation of the array [1, 2, 3, 4, 5].


In [9]:
list_array=np.array([1,2,3,4,5])
np.sum(list_array)

15

In [10]:
list_array=np.array([1,2,3,4,5])
np.mean(list_array)

3.0

In [11]:
list_array=np.array([1,2,3,4,5])
np.std(list_array)

1.4142135623730951

Reshape the array [1, 2, 3, 4, 5, 6] into a 2x3 array.

Explore Reshape

In [12]:
list_arr=np.array([1,2,3,4,5,6])
np.reshape(list_arr,(2,3))

array([[1, 2, 3],
       [4, 5, 6]])


# **2. Indexing and Slicing:**


Create a 5x5 array with random integers.


In [13]:
import numpy as np
random_array = np.random.randint(0, 10, size=(5, 5))
print(random_array)

[[3 8 9 4 2]
 [1 7 4 8 6]
 [9 9 1 5 2]
 [8 3 8 3 8]
 [2 1 9 6 2]]


Replace all values in the sub-array with a specific value.

In [14]:
random_array = np.random.randint(0, 10, size=(5, 5))
random_array[1:4, 1:4] = 44
print(random_array)

[[ 7  8  1  2  4]
 [ 4 44 44 44  9]
 [ 3 44 44 44  8]
 [ 7 44 44 44  7]
 [ 6  4  6  2  0]]


Extract the subarray [[3, 4], [7, 8]] from the array [[1, 2], [3, 4], [5, 6], [7, 8]].

In [15]:
my_array=np.array([[1, 2], [3, 4], [5, 6], [7, 8]])
subarray=my_array[1:2]
print(subarray)

[[3 4]]


In [16]:
my_array=np.array([[1, 2], [3, 4], [5, 6], [7, 8]])
subarray=my_array[3:]
print(subarray)

[[7 8]]



# **3. Broadcasting:**

Create a 2D array of shape (3, 3) with values from 0 to 2.


In [17]:
my_array=np.array([[0,1,2],[3,1,0],[1,0,2]])
my_array

array([[0, 1, 2],
       [3, 1, 0],
       [1, 0, 2]])

Add a 1D array of shape (3,) to each row of the 2D array using broadcasting.

In [18]:
array_1d=np.array([3,6,9])
array_2d=np.array([[0,1,2],[3,1,0],[1,0,2]])
add_arr=array_1d+array_2d
print(add_arr)

[[ 3  7 11]
 [ 6  7  9]
 [ 4  6 11]]


# **4. Concatenation and Splitting**


1.   Create two 2D arrays of shape (3, 3) with random integers.
2.   Concatenate them horizontally and vertically.
3.   Split the concatenated arrays back into the original arrays.

In [19]:
random_array_1=np.random.randint(0,10,size=(3,3))
random_array_2=np.random.randint(10,18, size=(3,3))
concantenate_horizantal=np.hstack((random_array_1,random_array_2))
print("concantenate_horizantal")
print(concantenate_horizantal)
split_horizantal=np.hsplit(concantenate_horizantal,2)
print("split_horizantal")
print(split_horizantal[0])
print(split_horizantal[1])

concantenate_horizantal
[[ 6  8  4 11 17 15]
 [ 6  6  0 16 10 13]
 [ 7  8  5 10 16 17]]
split_horizantal
[[6 8 4]
 [6 6 0]
 [7 8 5]]
[[11 17 15]
 [16 10 13]
 [10 16 17]]


In [20]:
concantenate_vertical=np.vstack((random_array_1,random_array_2))
print("concantenate_vertical")
print(concantenate_vertical)
split_vertical=np.vsplit(concantenate_vertical,2)
print("split_vertical")
print(split_vertical[0])
print(split_vertical[1])

concantenate_vertical
[[ 6  8  4]
 [ 6  6  0]
 [ 7  8  5]
 [11 17 15]
 [16 10 13]
 [10 16 17]]
split_vertical
[[6 8 4]
 [6 6 0]
 [7 8 5]]
[[11 17 15]
 [16 10 13]
 [10 16 17]]


# **Bonus Question**

Find mode of this array  = [1,2,1,2,3,4,5,6,8,9,1,2,2,22,21,1,1,1,1,2,5]

Hint: Use count and also loop

In [21]:
from scipy import stats
array=np.array([1,2,1,2,3,4,5,6,8,9,1,2,2,22,21,1,1,1,1,2,5])
print(stats.mode(array))

ModeResult(mode=1, count=7)


In [ ]:
array=np.array([1,2,1,2,3,4,5,6,8,9,1,2,2,22,21,1,1,1,1,2,5])
y=np.count()

# **Notes**


1.   All the Questions carry Equal Points (2 points)

2.   Bonus Question carry 5 points

3.   Review lecture for any query

Good Luck!

